services:
  redis:
    image: redis:alpine
    networks:
      - ghana-vote-net

  db:
    image: postgres:15-alpine
    env_file:
      - ./config/db-config.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - ghana-vote-net

  vote:
    build: ./vote
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    volumes:
      - ./config:/config
    depends_on:
      - redis
    networks:
      - ghana-vote-net

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
    env_file:
      - ./config/db-config.env
    volumes:
      - ./config:/config
    depends_on:
      - redis
      - db
    networks:
      - ghana-vote-net

  result:
    build: ./result
    ports:
      - "5001:80"
    env_file:
      - ./config/db-config.env
    volumes:
      - ./config:/config
    depends_on:
      - db
    networks:
      - ghana-vote-net

networks:
  ghana-vote-net:

volumes:
  postgres-data: